name: "PR Validation - Title, Description & Version Check"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # We need to compare the last commit

      - name: Check PR Title and Description
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title.trim();
            const body = pr.body ? pr.body.trim() : "";

            if (!title) {
              core.setFailed("❌ PR must have a title!");
            }
            if (!body) {
              core.setFailed("❌ PR must have a description!");
            }

      - name: Check for Version Bump & Release Notes
        run: |
          git diff HEAD^ HEAD -- package.json | grep '"version":' > version.diff || true

          if [ -s version.diff ]; then
            echo "🔍 Version change detected!"

            PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
            
            if [[ -z "$PR_BODY" || ! "$PR_BODY" =~ "## Release Notes" ]]; then
              echo "❌ Version changed but no release notes found!"
              exit 1
            fi

            echo "✅ Release notes are present."
          else
            echo "✅ No version change detected, skipping release notes check."
          fi
