name: "PR Title & Description Check"

on:
  pull_request:
    types: [opened, edited]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title and Description
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;

            if (!pr.title || pr.title.trim() === "") {
              core.setFailed("❌ PR must have a title!");
            }

            if (!pr.body || pr.body.trim() === "") {
              core.setFailed("❌ PR must have a description!");
            }
