name: Release

on:
  push:
    branches:
      - main # Trigger when pushing to main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history to get previous tags

      - name: Get Latest Tag
        id: last_tag
        run: echo "LAST_TAG=$(git describe --tags --abbrev=0 --always)" >> $GITHUB_ENV

      - name: Get Current Version
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Generate Release Notes
        run: |
          echo "### 🚀 Release Notes for v${{ env.VERSION }}" > release-notes.md
          echo "" >> release-notes.md
          echo "#### Merged PRs:" >> release-notes.md
          echo "" >> release-notes.md
          gh pr list --search "is:merged merged:>${{ env.LAST_TAG }}" --json title,body,number \
          --jq '.[] | "- **\(.title)** (#\(.number))\n  \(.body // "No description provided.")"' >> release-notes.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: release-notes.md
          draft: false
          prerelease: false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
