name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write # Allow creating releases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest version from package.json
        id: version
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Generate release notes from PR titles
        id: release_notes
        run: |
          echo "### 🚀 Release Notes for v${{ env.VERSION }}" > release-notes.md
          echo "" >> release-notes.md
          echo "#### Merged PRs:" >> release-notes.md
          echo "" >> release-notes.md
          gh pr list --state merged --limit 10 --json title --jq '.[].title' | awk '{print "- "$0}' >> release-notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: release-notes.md
          draft: false
          prerelease: false
